algoritmo "maioridade"
// Função :  verificar a idade
// Autor :
// Data : 18/05/2023
// Seção de Declarações 
var

nome: caractere
idade: inteiro

inicio

Escreval("Conte para mim o seu nome")
leia(nome)
Escreval("qual sua idade",nome)
leia(idade)

se(idade>=18)entao
    Escreval("Legal",nome,"voce é maior de idade!")
senao
    Escreval("Vish",nome,"voce ainda é de menor")
fimse

fimalgoritmo
