algoritmo "real em dollar"
// Função :
// Autor :
// Data : 30/03/2023
// Seção de Declarações 
var

cotacao, quantidade, total : real

inicio
//esntrada
escreval("quantos reais voce tem?")
leia(quantidade)
escreval("qual a cotacao do dolar")
leia(cotacao)

//processamento
total<- quantidade/cotacao

//saida
escreval("-------------------------")
escreval("voce tem um total de U$$", total)

fimalgoritmo
